version: "3"
services:
  apisix:
    image: apache/apisix:3.1.0-debian
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
    networks:
      apisix:

  openaiapi:
    build: openaiapi
    ports:
      - "8080:8080"
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
